### ISSUE TITLE
Error when using --check

### ISSUE THREAD

**Issue by jenrik** [Duckle29/ansible-dhparams#3]
When running `ansible-playbook` with the `--check` argument an error is reported and the playbook execution halts. This can likely be resolved by setting the `creates` or `removes` setting on the shell module in "Get current key-size", [see the module documentation for detail](https://docs.ansible.com/ansible/latest/modules/shell_module.html).

The following is the output from `ansible-playbook --check ...`:
```
TASK [include_role : duckle29.dhparam] *****************************************************************************************************

TASK [duckle29.dhparam : Ensure openssl is installed] **************************************************************************************
ok: [REDACTED]

TASK [duckle29.dhparam : Ensure remote folder is present] **********************************************************************************
ok: [REDACTED]

TASK [duckle29.dhparam : Get current key-size] *********************************************************************************************
skipping: [REDACTED]

TASK [duckle29.dhparam : debuginfo] ********************************************************************************************************
fatal: [REDACTED]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'stdout'\n\nThe error appears to be in '/home/user/.ansible/roles/duckle29.dhparam/tasks/main.yml': line 26, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: debuginfo\n  ^ here\n"} 
```

**Comment by jenrik** [comment]
A temporary workaround for users of this role is to add the following condition to the `include_role` statement
```
when: not ansible_check_mode
```

**Comment by Duckle29** [comment]
No clue why I only now saw this issue today. Been a while since I've used this.

I'm assuming something like:

```yaml
- name: Get current key-size
  ansible.builtin.shell: 
    removes: {{ dhparams_remote_directory }}/{{ dhparams_filename }}
    cmd:  >-
      openssl dhparam -in
      '{{ dhparams_remote_directory }}/{{ dhparams_filename }}'
      -text | grep -i 'dh parameters:' |
      sed 's/.*(\([0-9]\{1,\}\) bit).*/\1/'
  register: dhparams_remote_key_size
  changed_when: false
  ignore_errors: true
  
  ```  
might work?
